 #jar deployment

- name: deploy-jar
  hosts: all
  remote_user: pine64

  tasks:
      - copy: 
         src: target/btcminer-jar-with-dependencies.jar
         dest: /home/pine64/btcminer/btcminer.jar
         owner: pine64
         group: pine64
  
  
  